config/routes.rb
Rails.application.routes.draw do

  root 'flights#flights'
  get '/flights', to: 'flights#flights'

  get '/booking', to: 'bookings#new'
  post '/booking', to: 'bookings#create'
  get '/bookings', to: 'bookings#index'
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :departing_flights, class_name: "Flight", foreign_key: :start_airport_id
  has_many :arriving_flights, class_name: "Flight", foreign_key: :end_airport_id
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :passenger
  belongs_to :flight
  accepts_nested_attributes_for :passenger
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :to_airport, class_name: "Airport", foreign_key: :end_airport_id
  belongs_to :from_airport, class_name: "Airport", foreign_key: :start_airport_id
  has_many :bookings, dependent: :destroy
  has_many :passengers, through: :bookings
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  has_many :bookings, dependent: :destroy
  has_many :flights, through: :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @flight = Flight.find(params[:booking][:flight_id])
    @booking = @flight.bookings.build
    @passengers = []
    params[:booking][:num_of_tickets].to_i.times do
      @passengers << Passenger.new
    end
  end

  def create
    params[:booking][:passenger_attributes].each do |key, value|
        @passenger = Passenger.new(user_params(value))
        @passenger.save
        @booking = @passenger.bookings.new(flight_id: params[:booking][:flight_id])
        @booking.save
        PassengerMailer.thank_you(@booking).deliver_later
    end
    redirect_to bookings_path
  end

  def index
    @bookings = Booking.includes(:passenger).includes(:flight).all
  end

  private

  def user_params(u_params)
    u_params.permit(:name, :email, :age, :sex)
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController

  def flights
    @flights = Flight.includes(:to_airport, :from_airport)
                      .all.order(flight_start: :asc)
    @dates = @flights.map { |f| f.flight_start.to_date }.uniq
    @from = @flights.map { |f| [f.from_airport.name, f.start_airport_id]}.uniq.sort
    @to = @flights.map { |f| [f.to_airport.name, f.end_airport_id]}.uniq.sort
    @filtered_flights = []

    unless params[:flight].nil?
      @flights.map { |f| @filtered_flights << f if matched?(f) }
    end
  end

  private
    def matched?(flight)
      params[:flight][:to_airport] == flight.end_airport_id.to_s &&
      params[:flight][:from_airport] == flight.start_airport_id.to_s &&
      params[:flight][:flight_start] == flight.flight_start.to_date.to_s
    end
end

app/controllers/passengers_controller.rb
class PassengersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/passengers_helper.rb
module PassengersHelper
end

app/views/bookings/index.html.erb
<table class="table table-striped text-center">
  <thead>
    <tr>
      <th class="text-center">Flight ID</th>
      <th class="text-center">From</th>
      <th class="text-center">To</th>
      <th class="text-center">Date</th>
      <th class="text-center">Duration</th>
      <th class="text-center">Name</th>
      <th class="text-center">Email</th>
      <th class="text-center">Sex</th>
      <th class="text-center">Age</th>
    </tr>
  </thead>
  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.flight_id %></td>
        <td><%= booking.flight.from_airport.name %></td>
        <td><%= booking.flight.to_airport.name %></td>
        <td><%= booking.flight.flight_start %></td>
        <td><%= booking.flight.flight_duration %></td>
        <td><%= booking.passenger.name %></td>
        <td><%= booking.passenger.email %></td>
        <td><%= booking.passenger.sex %></td>
        <td><%= booking.passenger.age %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/bookings/new.html.erb
<%= form_for @booking, url: booking_path do |f| %>
  <table class="table table-striped text-center">
    <thead>
      <tr>
        <th class="text-center">From</th>
        <th class="text-center">To</th>
        <th class="text-center">Flight Date</th>
        <th class="text-center">Flight Duration(hours)</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @flight.from_airport.name %></td>
        <td><%= @flight.to_airport.name %></td>
        <td><%= @flight.flight_start %></td>
        <td><%= @flight.flight_duration %></td>
      </tr>
    </tbody>
  </table>
  <%= f.hidden_field :flight_id, value: params[:booking][:flight_id] %>
  <%= f.fields_for :passenger, @passengers do |passenger_fields| %>
  <div class="form-group form-inline text-center">
    <%= passenger_fields.label :name, "Name: " %>
    <%= passenger_fields.text_field :name, class: "form-control" %>

    <%= passenger_fields.label :email, "Email: " %>
    <%= passenger_fields.email_field :email, class: "form-control" %>

    <%= passenger_fields.label :age, "Age: " %>
    <%= passenger_fields.text_field :age, class: "form-control" %>

    <%= passenger_fields.label :sex, "Sex: " %>
    <%= passenger_fields.select :sex, options_for_select(["Male", "Female"]), {}, { class: 'form-control' } %>
  </div>
  <% end %>
  <%= f.submit "Create booking", class: "btn btn-default btn-block" %>
<% end %>

app/views/flights/_list_of_flights.html.erb
<% if @filtered_flights.any? %>
  <%= form_for :booking, url: booking_path, method: :get do |f| %>
    <table class="table table-striped text-center">
      <tr>
        <th class="text-center">From</th>
        <th class="text-center">To</th>
        <th class="text-center">Flight Date</th>
        <th class="text-center">Flight Duration(hours)</th>
        <th class="text-center">Select</th>
      </tr>
      <% @filtered_flights.each do |flight| %>
        <tr>
          <td><%= flight.from_airport.name %></td>
          <td><%= flight.to_airport.name %></td>
          <td><%= flight.flight_start %></td>
          <td><%= flight.flight_duration %></td>
          <td><%= f.radio_button :flight_id, flight.id %></td>
        </tr>
      <% end %>
    </table>
    <%= f.hidden_field :num_of_tickets, value: params[:flight][:num_of_tickets] %>
    <%= f.submit "Fill in booking information", class: "btn btn-default btn-block" %>
  <% end %>
<% else %>
  <h4 class="text-center">No Flights Found</h4>
<% end %>

app/views/flights/_search_form.html.erb
<%= form_for :flight, url: '/flights',
             method: :get, html: {class: 'form-inline text-center'} do |f| %>
  <div class="form-group">
    <%= f.label :from_airport, "From: " %>
    <%= f.select :from_airport, options_for_select(@from), {}, { class: 'form-control' } %>
  </div>

  <div class="form-group">
    <%= f.label :to_airport, "To: " %>
    <%= f.select :to_airport, options_for_select(@to), {}, { class: 'form-control' } %>
  </div>

  <div class="form-group">
    <%= f.label :flight_start, "Date: " %>
    <%= f.select :flight_start, options_for_select(@dates), {}, { class: 'form-control' } %>
  </div>

  <div class="form-group">
    <%= f.label :num_of_tickets, "Tickets: " %>
    <%= f.select :num_of_tickets, options_for_select([1,2,3,4]), {}, { class: 'form-control' } %>
  </div>
  <br /><br />
  <%= f.submit "Search for flights", class: "btn btn-default btn-block" %>
<% end %>
<hr />

app/views/flights/flights.html.erb
<div class="panel panel-default">
  <div class="panel-heading text-center">
    <h3 class="panel-title">Choose your flight</h3>
  </div>
  <div class="panel-body">
    <%= render 'search_form' %>
    <%= render 'list_of_flights' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFlightBooker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render 'shared/header' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_header.html.erb
<div class="page-header text-center">
  <h1><%= link_to "FLIGHTS", flights_path %>/<%= link_to "BOOKINGS", bookings_path %></h1>
</div>